{
  "formatVersion": "1.1",
  "component": {
    "group": "xh.rabbit.core",
    "module": "core",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.1.aar",
          "url": "core-0.0.1.aar",
          "size": 43294,
          "sha512": "feccc8c96b7299ba3f0099ee22541f8ad087356d4a3fc75847fd1a137e16fdc751f8100717a52840e3b0ea28c587c8ae5684fb482131c1f8d7a29aa9081034af",
          "sha256": "a827782bf0c8e5df449f73243711f05471c7fe9beb08c61a00c7264901e29eb2",
          "sha1": "7fa9516553453dbdef3c8cc817de52904ba9005e",
          "md5": "5e93dff1c39483eec4935abcec9034e0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.1.aar",
          "url": "core-0.0.1.aar",
          "size": 43294,
          "sha512": "feccc8c96b7299ba3f0099ee22541f8ad087356d4a3fc75847fd1a137e16fdc751f8100717a52840e3b0ea28c587c8ae5684fb482131c1f8d7a29aa9081034af",
          "sha256": "a827782bf0c8e5df449f73243711f05471c7fe9beb08c61a00c7264901e29eb2",
          "sha1": "7fa9516553453dbdef3c8cc817de52904ba9005e",
          "md5": "5e93dff1c39483eec4935abcec9034e0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.0.1-sources.jar",
          "url": "core-0.0.1-sources.jar",
          "size": 30491,
          "sha512": "c5a42ff50a3610ca0ad031f5fbb9973069639dd67830f0bab636e944fc18ff305ceda453b4dccfd758533eff8f5651edf28f0b5fef1bc3b0e46fd07e4e0acaed",
          "sha256": "5cb55030d5def981d6c13cbf898cb36b5aedfb1b31eb06e7d7400121536ef746",
          "sha1": "5fe4ffed350899e4202fa3ced322209afc7a0911",
          "md5": "bffbb3d3bea783122776bb1c690508d4"
        }
      ]
    }
  ]
}
